version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8091:80"
    volumes:
      - ./public:/var/www/html
      - ./public/var:/var/www/html/var
      - ./var:/var/www/var
      - ./apache-config:/etc/apache2
      - ./var/garlic-hub.sqlite:/var/www/var/garlic-hub.sqlite