version: '3.8'

services:
  app:
    image: php:8.3-apache
    ports:
      - "443:443"
    volumes:
      - ./public:/var/www/html
      - ./public/var:/var/www/html/var
      - ./var:/var/www/var
      - ./apache/conf:/usr/local/apache2/conf/
      - ./apache/ssl:/usr/local/apache2/conf/ssl
    depends_on:
      - db

  db:
    image: sqlite:3.45.1
    volumes:
      - ./var/garlic-hub.sqlite:/var/lib/sqlite/garlic-hub.sqlite
volumes:
  html:
  app-var-html:
  app-var:
  db-data:
  apache-ssl: