services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: garlic-hub
    ports:
      - "8090:80"
    volumes:
      - garlic-hub-public-var:/var/www/public/var
      - garlic-hub-var:/var/www/var

# for later use
volumes:
  garlic-hub-public-var:
  garlic-hub-var:
