ServerName _

<VirtualHost *:80>
    ServerAdmin garlic@saghiadinos.de
    DocumentRoot "/var/www/public"
    <Directory "/var/www/public/">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    Alias /device-logs /var/www/var/devicelogs
    <Directory "/var/www/var/devicelogs">
        DAV On
        Options None
        AllowOverride None
        # maximun 20MB
        LimitRequestBody 20971520

        <RequireAll>
            Require method PUT
            Require expr "%{REQUEST_URI} =~ m#\.xml$#"
        </RequireAll>
    </Directory>

    ErrorLog /var/www/var/weblogs/error.log
    CustomLog /var/www/var/weblogs/access.log combined
</VirtualHost>
