controllers_main:
    resource: ../src/Controller/
    type: attribute

controllers_modules:
    resource: ../src/Modules/
    type: attribute
    exclude: '../src/Modules/*/{Service,Model}'


# remember php bin/console cache:clear --env=prod