name: garlic-hub Image CI

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: sagiadinos
        password: ${{ secrets.SAGIADINOS }}

    - name: Build the Docker image
      run: docker compose build
      
    - name: Push image manually
      run: |
        docker tag docker-webserver sagiadinos/garlic-hub:latest
        docker push sagiadinos /garlic-hub:latest

